### CADASTRA UM USUÁRIO
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Mateus Matos Leonardo",
  "email": "mateusmatosleonardo@gmail.com",
  "cpf": "033.333.222-33",
  "phone": "88981820222",
  "password": "root@123"
}

### OBTÉM TODOS OS USUÁRIOS CADASTRADOS
GET http://localhost:3333/users
